# Practical Exam: Supermarket Loyalty

International Essentials is an international supermarket chain.

Shoppers at their supermarkets can sign up for a loyalty program that provides rewards each year to customers based on their spending. The more you spend the bigger the rewards. 

The supermarket would like to be able to predict the likely amount customers in the program will spend, so they can estimate the cost of the rewards. 

This will help them to predict the likely profit at the end of the year.

## Data

The dataset contains records of customers for their last full year of the loyalty program.

| Column Name | Criteria                                                |
|-------------|---------------------------------------------------------|
|customer_id | Unique identifier for the customer. </br>Missing values are not possible due to the database structure. |
|spend | Continuous. </br>The total spend of the customer in their last full year. This can be any positive value to two decimal places. </br>Missing values should be replaced with 0. |
|first_month | Continuous. </br>The amount spent by the customer in their first month of the year. This can be any positive value, rounded to two decimal places. </br>Missing values should be replaced with 0. |
| items_in_first_month | Discrete. </br>The number of items purchased in the first month. Any integer value greater than or equal to zero. </br>Missing values should be replaced by 0. |  
| region | Nominal. </br>The geographic region that the customer is based in. One of four values Americas, Asia/Pacific, Europe, Middle East/Africa. </br>Missing values should be replaced with "Unknown". |
| loyalty_years | Oridinal. </br>The number of years the customer has been a part of the loyalty program. One of five ordered categories, '0-1', '1-3', '3-5', '5-10', '10+'. </br>Missing values should be replaced with '0-1'.|
| joining_month | Nominal. </br>The month the customer joined the loyalty program. One of 12 values "Jan", "Feb", "Mar", "Apr", etc. </br>Missing values should be replaced with "Unknown".|
| promotion | Nominal. </br>Did the customer join the loyalty program as part of a promotion? Either 'Yes' or 'No'. </br>Missing values should be replaced with 'No'.|

# Task 1

Before you fit any models, you will need to make sure the data is clean. 

The table below shows what the data should look like. 

Create a cleaned version of the dataframe. 

 - You should start with the data in the file "loyalty.csv". 

 - Your output should be a dataframe named `clean_data`. 

 - All column names and values should match the table below.

| Column Name | Criteria                                                |
|-------------|---------------------------------------------------------|
|customer_id | Unique identifier for the customer. </br>Missing values are not possible due to the database structure. |
|spend | Continuous. </br>The total spend of the customer in their last full year. This can be any positive value to two decimal places. </br>Missing values should be replaced with 0. |
|first_month | Continuous. </br>The amount spent by the customer in their first month of the year. This can be any positive value, rounded to two decimal places. </br>Missing values should be replaced with 0. |
| items_in_first_month | Discrete. </br>The number of items purchased in the first month. Any integer value greater than or equal to zero. </br>Missing values should be replaced by 0. |  
| region | Nominal. </br>The geographic region that the customer is based in. One of four values Americas, Asia/Pacific, Europe, Middle East/Africa. </br>Missing values should be replaced with "Unknown". |
| loyalty_years | Oridinal. </br>The number of years the customer has been a part of the loyalty program. One of five ordered categories, '0-1', '1-3', '3-5', '5-10', '10+'. </br>Missing values should be replaced with '0-1'.|
| joining_month | Nominal. </br>The month the customer joined the loyalty program. One of 12 values "Jan", "Feb", "Mar", "Apr", etc. </br>Missing values should be replaced with "Unknown".|
| promotion | Nominal. </br>Did the customer join the loyalty program as part of a promotion? Either 'Yes' or 'No'. </br>Missing values should be replaced with 'No'.|

In [219]:
#Cell for Task 1 
#Inspect and clean data in preparation for analysis in Task 2 

import pandas as pd
import numpy as np 

df = pd.read_csv("loyalty.csv")

print(df.isna().sum())

#Run .info() to determine missing data and data types 
#df.info()
#Joining Month column missing values, will also have to change some category types?
#No edits needed to customer ID as missing values are not possible 
#Edit the spend 

df["spend"].fillna(0, inplace=True)

df["first_month"].replace(".", 0, inplace=True)
df["first_month"].fillna(0, inplace=True)

df["first_month"] = df["first_month"].astype(float)

df["items_in_first_month"].fillna(0, inplace=True)

#df["region"].fillna("Unknown", inplace=True) #not needed since there are no strange/missing values
df["region"] = df["region"].astype("category")

df["loyalty_years"].fillna("0-1", inplace=True)
df["loyalty_years"] = df["loyalty_years"].astype("category")

df["joining_month"].fillna("Unknown", inplace=True)
df["joining_month"] = df["joining_month"].astype(str)

df["promotion"].fillna("No", inplace=True)
df["promotion"] = df["promotion"].astype(str)
df["promotion"].replace("YES", "Yes", inplace=True)
df["promotion"].replace("NO", "No", inplace=True)

df.info()
clean_data = df.copy()

customer_id               0
spend                     0
first_month               0
items_in_first_month      0
region                    0
loyalty_years             0
joining_month           125
promotion                 0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1246 entries, 0 to 1245
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           1246 non-null   int64
 1   spend                 1246 non-null   float64
 2   first_month           1246 non-null   float64
 3   items_in_first_month  1246 non-null   int64
 4   region                1246 non-null   category
 5   loyalty_years         1246 non-null   category
 6   joining_month         1246 non-null   object
 7   promotion             1246 non-null   object
dtypes: category(2), float64(2), int64(2), object(2)
memory usage: 61.4+ KB

# Task 2 

The team at International Essentials have told you that they have always believed that the number of years in the loyalty scheme is the biggest driver of spend. 

Producing a table showing the difference in the average spend by number of years in the loyalty programme along with the variance to investigate this question for the team.

 - You should start with the data in the file 'loyalty.csv'.

 - Your output should be a data frame named `spend_by_years`. 

 - It should include the three columns `loyalty_years`, `avg_spend`, `var_spend`. 

 - Your answers should be rounded to 2 decimal places.

In [220]:
# Use this cell to write your code for Task 2

clean_data
#Calculate the average spend by the number of loyalty years along with the variance 
spend_by_years = clean_data.groupby('loyalty_years')['spend'].agg(['mean', 'var']).reset_index()
spend_by_years.columns = ['loyalty_years', 'avg_spend', 'var_spend']

spend_by_years = spend_by_years.round(2)

spend_by_years

  loyalty_years  avg_spend  var_spend
0           0-1     110.56       9.30
1           1-3     129.31       9.65
2           10+     117.41      16.72
3           3-5     124.55      11.09
4          5-10     135.15      14.10

# Task 3

Fit a baseline model to predict the spend over the year for each customer.

 1. Fit your model using the data contained in “train.csv” </br></br>

 2. Use “test.csv” to predict new values based on your model. You must return a dataframe named `base_result`, that includes `customer_id` and `spend`. The `spend` column must be your predicted values.

In [221]:
# Use this cell to write your code for Task 3

#Fit a baseline model to predict the spend over the year for each customer.

test_data = pd.read_csv('test.csv')
train_data = pd.read_csv('train.csv')

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

X_new = train_data.drop(columns=['customer_id', 'spend'])
y_new = train_data['spend']

categorical_cols_new = [col for col in X_new.columns if X_new[col].dtype == 'object']

# Creating a transformer for preprocessing in the new dataset
preprocessor_new = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols_new),
    ],
    remainder='passthrough'  # keeping other columns untouched
)

model_new = Pipeline(steps=[
    ('preprocessor', preprocessor_new),
    ('regressor', LinearRegression())
])

#Fit the model with the new dataset
model_new.fit(X_new, y_new)

# The model is now trained with the new dataset. 
# If a validation dataset is provided, we can make predictions on it.
"Model trained successfully with the new dataset."

# Preparing the validation data (similar to the training data preparation)
X_validation = test_data.drop(columns=['customer_id'])

test_data['spend'] = model_new.predict(X_validation)

base_result = test_data[['spend', 'customer_id']]

base_result

          spend  customer_id
0    140.699635            5
1    148.730908            7
2    140.810374           16
3    150.649676           17
4    153.628820           19
..          ...          ...
245  134.869759         1216
246  148.542586         1225
247  136.969016         1231
248  129.885720         1242
249  148.518405         1243

[250 rows x 2 columns]

In [222]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           250 non-null    int64
 1   first_month           250 non-null    float64
 2   items_in_first_month  250 non-null    int64
 3   region                250 non-null    object
 4   loyalty_years         250 non-null    object
 5   joining_month         250 non-null    object
 6   promotion             250 non-null    object
 7   spend                 250 non-null    float64
dtypes: float64(2), int64(2), object(4)
memory usage: 15.8+ KB

# Task 4

Fit a comparison model to predict the spend over the year for each customer.

 1. Fit your model using the data contained in “train.csv” </br></br>

 2. Use “test.csv” to predict new values based on your model. You must return a dataframe named `compare_result`, that includes `customer_id` and `spend`. The `spend` column must be your predicted values.

In [223]:
# Use this cell to write your code for Task 4

#Fit a comparison model to predict the spend over the year for each customer.

from sklearn.ensemble import RandomForestRegressor
train_df_comparison = train_data


X_comparison = train_df_comparison.drop(columns=['customer_id', 'spend'])
y_comparison = train_df_comparison['spend']

categorical_cols_comparison = [col for col in X_comparison.columns if X_comparison[col].dtype == 'object']

# Creating a transformer for preprocessing in the new dataset for the comparison model
preprocessor_comparison = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols_comparison),
    ],
    remainder='passthrough'  # keeping other columns untouched
)

# Creating a pipeline with preprocessing and the Random Forest Regressor for the comparison model

model_comparison = Pipeline(steps=[
    ('preprocessor', preprocessor_comparison),
    ('regressor', RandomForestRegressor(n_estimators=100, random_state=42))
])

model_comparison.fit(X_comparison, y_comparison)
validation_df_comparison = test_data

X_validation_comparison = validation_df_comparison.drop(columns=['customer_id', 'spend'])

validation_df_comparison['spend'] = model_comparison.predict(X_validation_comparison)

compare_result = validation_df_comparison[['spend', 'customer_id']]

compare_result

          spend  customer_id
0    140.538600            5
1    148.856400            7
2    141.131200           16
3    150.796600           17
4    153.621800           19
..          ...          ...
245  134.807700         1216
246  148.520707         1225
247  136.973200         1231
248  129.725500         1242
249  148.577400         1243

[250 rows x 2 columns]